// This file is generated by build.rs, do not modify

use crate::{Word, word};

// KERNEL PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed kernel procedures.
pub const KERNEL_PROCEDURES: [Word; 50] = [
    // account_get_initial_commitment
    word!("0x428fc7b1fda493bfda62f4f775dea0b5d2f67fced462b677f3e2cbd801eb6c24"),
    // account_compute_commitment
    word!("0xeae60b8eea84883c07323f92dbbcc9c6d579056968ae3f5bdc1f23028494056b"),
    // account_get_id
    word!("0x73a3767105fff911706a0c8564703e7e3d6912a1b5eb604b71476499b7bb5a1e"),
    // account_get_nonce
    word!("0xf689e1ba8deaa0b39addb6a36aa922e3c9b9ed172a9930a11a3a00f050c26673"),
    // account_incr_nonce
    word!("0x3a3ea1878b567ea5103d045fd30b981bfa4dda12ba06ea93957942b787ee269e"),
    // account_get_code_commitment
    word!("0xfad445052d9bc370550060fa2e5baad7b2cec350306c580cad8c94f57f4fc936"),
    // account_get_initial_storage_commitment
    word!("0xcf3f199f8b679d6a18fa3c581d19c9644d86a4ece01ce0a4b1841be584237586"),
    // account_compute_storage_commitment
    word!("0x398d217aa18f0a3ce52198ca30d8b97edae88f0f247d4cbfa7073dc01dcfd1fa"),
    // account_get_item
    word!("0x6c4a309164216cd0ade284be5dafdf908c843415ea4e3c8076da222a35242ddf"),
    // account_get_initial_item
    word!("0x608c220fad2506e8c8cb91e3616e5329734b8084dc24cd0e29bf2b2afc3b459c"),
    // account_set_item
    word!("0xea6399e82bded79f07e787945a9a741097b7adb1c90b13fbf6edcdd5b8223f99"),
    // account_get_map_item
    word!("0x18db5479e15631e99b5cdd9e862ad292b02882e3b980f20766e50be455b3d265"),
    // account_get_initial_map_item
    word!("0xb51370bdd09abf4fd78fe227a8d69df6e70095b8146a40bf686a0b6184e73086"),
    // account_set_map_item
    word!("0x811e8cea8f54547838af32da86001a143c269f20b50dcad63e021eef5caf87d2"),
    // account_get_initial_vault_root
    word!("0x02649bba877c3f2485e19b13124212f308c496164daf5b67c5d6cac5cc1efa93"),
    // account_get_vault_root
    word!("0x06d2ed6e186f5a6ed429393c125d3299b8b8c9d374d4a70c07223270a226e4ee"),
    // account_add_asset
    word!("0x5c524e85edb7169a227ca22a0bd3b7358db47759bba0fb24848364ff02bfba09"),
    // account_remove_asset
    word!("0xd8a9ec09086027ee1c3123a484fe7b26c71ae8c67228556e84fefcfa4baad703"),
    // account_get_asset
    word!("0xfe9a9b1c47b2c4a26eba5e5c8f768c326b91eaeb4035d4543399bb47bcb17969"),
    // account_get_initial_asset
    word!("0x198e7beb67775fdf25509dc1c58bf8dfbd3b420dbe1dd614e4875623d2f4733f"),
    // account_compute_delta_commitment
    word!("0x1ee26ba427f48650d96557df9d344b2ed231ba4d798e0aca2deda41b3582cfc0"),
    // account_get_num_procedures
    word!("0xfd0ba549c2eb309268f9285ea2f689c50b70f625f79767ecbfc2827e61c76b01"),
    // account_get_procedure_root
    word!("0x46eca9419660d7b453da7926c22156d2e7e56f8d6855dad3044c359eb7a56eca"),
    // account_was_procedure_called
    word!("0xcdd2f93e20df0220a34f123fd8b99edbef4d8534db6f88567f1cad5507149161"),
    // account_has_procedure
    word!("0xc6d3f1dcbe531f4aeb6b6a7b2cebd9fbc460f473ac3d25a9a6a6febfbb572777"),
    // faucet_mint_asset
    word!("0x87930eb2423eb36cf2f12a69c5fb2f04bba5b0b53d16724cf4870d91f1705549"),
    // faucet_burn_asset
    word!("0x3852d2e07cfeb4e52c0cd133a4173df16bc74634fa3e0dda17ece289d538e200"),
    // input_note_get_metadata
    word!("0x447b342e38855a9402cde0ea52ecb5e4c1fe542b535a5364cb5caa8e94c82442"),
    // input_note_get_assets_info
    word!("0xe0817bed99fb61180e705b2c9e5ca8c8f0c62864953247a56acbc65b7d58c2d5"),
    // input_note_get_script_root
    word!("0x527036257e58c3a84cf0aa170fb3f219a4553db17d269279355ad164a2b90ac5"),
    // input_note_get_storage_info
    word!("0xb7f45ec34f7708355551dcf1f82c9c40e2c19252f8d5c98dcf9ef1aa0a3eb878"),
    // input_note_get_serial_number
    word!("0x25815e02b7976d8e5c297dde60d372cc142c81f702f424ac0920190528c547ee"),
    // input_note_get_recipient
    word!("0xd3c255177f9243bb1a523a87615bbe76dd5a3605fcae87eb9d3a626d4ecce33c"),
    // output_note_create
    word!("0x0ce0fbeb307de6ac9cd10b8b05a112d342ed3a8ff033cc3f49287561932ee989"),
    // output_note_get_metadata
    word!("0xd089109a5468cda774bdd6ef2347a2bc0cbe599e4cf324bfd0d830ddcf541b9b"),
    // output_note_get_assets_info
    word!("0xa4e1135421226f499a2c9cad5dfeb72c8a0aaf75a6269831d72d1f6ffa17f98b"),
    // output_note_get_recipient
    word!("0xac423c9a37cd0dbe9f9ded8ce7cc3289d6632d9cba858aa9ac15706278dec0db"),
    // output_note_add_asset
    word!("0x816d7dfeb746dae0c6c1aa7056a14c132552f223c71d8f1626892bc84b3947b5"),
    // output_note_set_attachment
    word!("0x3fa10be4130e1d87e18c3707f0abf8349c42b141f41ac4be360e2328ccc93137"),
    // tx_get_num_input_notes
    word!("0xfcc186d4b65c584f3126dda1460b01eef977efd76f9e36f972554af28e33c685"),
    // tx_get_input_notes_commitment
    word!("0xc3a334434daa7d4ea15e1b2cb1a8000ad757f9348560a7246336662b77b0d89a"),
    // tx_get_num_output_notes
    word!("0x6a55f7cc1d20a75c36d474a59476c32faded0f5ff327cf942a8bc0fc0bb576e4"),
    // tx_get_output_notes_commitment
    word!("0x35149a69681842b93abe0cac01db65f901f634cbbc3d3366404ffc1bdae77d41"),
    // tx_get_block_commitment
    word!("0xe474b491a64d222397fcf83ee5db7b048061988e5e83ce99b91bae6fd75a3522"),
    // tx_get_block_number
    word!("0x297797dff54b8108dd2df254b95d43895d3f917ab10399efc62adaf861c905ae"),
    // tx_get_block_timestamp
    word!("0x7903185b847517debb6c2072364e3e757b99ee623e97c2bd0a4661316c5c5418"),
    // tx_prepare_fpi
    word!("0x9b19a239c7bf6cccacc15b4739678c6e76d52efcb5bd9a0b885f8c425cf750f9"),
    // tx_exec_foreign_proc
    word!("0xb9f12424eb95660468ddc430c7d12f5036a64da0fe72faac14cd496abcf360d9"),
    // tx_get_expiration_delta
    word!("0x1e9cb08be26df46db852bf39c1f40d2b7fca686e23b058e2eec07b395723cfbd"),
    // tx_update_expiration_block_delta
    word!("0xc60e37f9a13f262a1df62654e083dc7e4c7d9897fdc7179e56b0789c72944193"),
];
