// This file is generated by build.rs, do not modify

use crate::{Word, word};

// KERNEL PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed kernel procedures.
pub const KERNEL_PROCEDURES: [Word; 50] = [
    // account_get_initial_commitment
    word!("0x1de52b747e823a098f3e146cf2e2b7c3f585a4424ec54c9022414d9ca2574375"),
    // account_compute_commitment
    word!("0xdcb7c06bc7617d49bcda33d1753e327cc744b9f83e2019d61eca016b33c527a7"),
    // account_get_id
    word!("0xd76288f2e94b9e6a8f7eeee45c4ee0a23997d78496f6132e3f55681efea809c4"),
    // account_get_nonce
    word!("0x4a1f11db21ddb1f0ebf7c9fd244f896a95e99bb136008185da3e7d6aa85827a3"),
    // account_incr_nonce
    word!("0xae55eb22b6f1f2c7e887c5d6bedab3f4d50182e98b4739e2736e9120d0377344"),
    // account_get_code_commitment
    word!("0x70e145a3456d5bec595d0cb40d9d87cb05a27c019ec7e226894c68bd032aa38d"),
    // account_get_initial_storage_commitment
    word!("0x91377c2852feb7a2798e54d7dbaa2d97000270ec4c0d0888b26d720a25ae0e84"),
    // account_compute_storage_commitment
    word!("0xb2425b7b89fdae430f815ee549b2e41e4c1590db9fa320841376402153815e73"),
    // account_get_item
    word!("0x20f4b61472db0bffc7d7f8c5d69327b42e25d1541ff032af1c1dd3d640bea963"),
    // account_get_initial_item
    word!("0x0c41cb06420236e80fa9c83169a94abff0b14e9ebc370e91ae220a5783fc4970"),
    // account_set_item
    word!("0x9cf05d83a1bf57d0f7f33ba3b9839104d530d959888c15c16c3c7a5fdba79af4"),
    // account_get_map_item
    word!("0xff6a081bfa6d066b2f70bdb9f7749df096ddb466fa748b59c0cc1ddc26fc24b8"),
    // account_get_initial_map_item
    word!("0x0faa9c57eebfc7409e1826ed4db0fef617a570b6b17f6d2e37c9dadad36a3861"),
    // account_set_map_item
    word!("0x11ebe3ce47e1a8a42e96c84f7d94e2455e911593d50ced0151277dd568746e26"),
    // account_get_initial_vault_root
    word!("0x46297d9ac95afd60c7ef1a065e024ad49aa4c019f6b3924191905449b244d4ec"),
    // account_get_vault_root
    word!("0x42a2bfb8eac4fce9bbf75ea15215b00729faeeaf7fff784692948d3f618a9bb7"),
    // account_add_asset
    word!("0x91a5276ebe971b2c25ec59e3226553aa4168d4ac68c0bcbdbc211d7b437bf7bd"),
    // account_remove_asset
    word!("0xc0d6a0f9d42cf16b8196663f63bd58bf19638e4abe7a7ab4d83c0d109bef9b76"),
    // account_get_asset
    word!("0x21dc0ef7e3475f28fbcf26636d9b58c3f7e349da7c7a36e85c1b49e50437fa65"),
    // account_get_initial_asset
    word!("0x8e1fabe016fa23523489a8aec0a0cc3804610b75c8b4a1774e46eb6a9d205cb5"),
    // account_compute_delta_commitment
    word!("0x09767ee5e29aeca91a57f3af3871bbfb3037681e193444b3f7af878894c1aaa3"),
    // account_get_num_procedures
    word!("0x53b5ec38b7841948762c258010e6e07ad93963bcaac2d83813f8edb6710dc720"),
    // account_get_procedure_root
    word!("0xa45796077477599813ea54d88a83dfca3e64b1c112117970d63a1c24f7cfef5a"),
    // account_was_procedure_called
    word!("0xc2e7b1e15072cf3ea8212ca6b3c35c7e093b585dc3cac20fc7804f6ad7641b2f"),
    // account_has_procedure
    word!("0xb0b63fdd01af0bcb4aacb2412e934cdc7691308647152d416c7ae4fc909da076"),
    // faucet_mint_asset
    word!("0x0378e38a593a1bbaca17708f7169f5b6d563fc7bbd9fb43c05b2e8686c38e27f"),
    // faucet_burn_asset
    word!("0xdfd6f18147c45a7f06984715b66fa7139ff5a27acf18060e58681b4c622c0472"),
    // input_note_get_metadata
    word!("0x447b342e38855a9402cde0ea52ecb5e4c1fe542b535a5364cb5caa8e94c82442"),
    // input_note_get_assets_info
    word!("0xe0817bed99fb61180e705b2c9e5ca8c8f0c62864953247a56acbc65b7d58c2d5"),
    // input_note_get_script_root
    word!("0x527036257e58c3a84cf0aa170fb3f219a4553db17d269279355ad164a2b90ac5"),
    // input_note_get_storage_info
    word!("0xb7f45ec34f7708355551dcf1f82c9c40e2c19252f8d5c98dcf9ef1aa0a3eb878"),
    // input_note_get_serial_number
    word!("0x25815e02b7976d8e5c297dde60d372cc142c81f702f424ac0920190528c547ee"),
    // input_note_get_recipient
    word!("0xd3c255177f9243bb1a523a87615bbe76dd5a3605fcae87eb9d3a626d4ecce33c"),
    // output_note_create
    word!("0x2bc7c67228d296ef791ba872d2dfc467f31dcf1fbf8cb13561af24092173d8f3"),
    // output_note_get_metadata
    word!("0x3db8427f20eb70603b72aa574a986506eb7216312004aeaf8b2a7e55d0049a48"),
    // output_note_get_assets_info
    word!("0xbbf90ac2a7e16ee6d2336f7389d5b972bf0c1fa9938405945b85f948bf24fc4f"),
    // output_note_get_recipient
    word!("0x1ce137f0c5be72832970e6c818968a789f65b97db34515bfebb767705f28db67"),
    // output_note_add_asset
    word!("0xe2cc1a8068bebb976b7f3d2a4c7c3cf5e7d9846743109ad656bedd1b40c47586"),
    // output_note_set_attachment
    word!("0xb950dadea783fb7d3903aeefd7ef7d253b085b20f6628597f85c8df21eee7df9"),
    // tx_get_num_input_notes
    word!("0xfcc186d4b65c584f3126dda1460b01eef977efd76f9e36f972554af28e33c685"),
    // tx_get_input_notes_commitment
    word!("0xc3a334434daa7d4ea15e1b2cb1a8000ad757f9348560a7246336662b77b0d89a"),
    // tx_get_num_output_notes
    word!("0x2511fca9c078cd96e526fd488d1362cbfd597eb3db8452aedb00beffee9782b4"),
    // tx_get_output_notes_commitment
    word!("0x8b9b29c837b5d0834f550d7f32703b35e2ff014b523dd581a09a0b94a925fcec"),
    // tx_get_block_commitment
    word!("0xe474b491a64d222397fcf83ee5db7b048061988e5e83ce99b91bae6fd75a3522"),
    // tx_get_block_number
    word!("0x297797dff54b8108dd2df254b95d43895d3f917ab10399efc62adaf861c905ae"),
    // tx_get_block_timestamp
    word!("0x7903185b847517debb6c2072364e3e757b99ee623e97c2bd0a4661316c5c5418"),
    // tx_start_foreign_context
    word!("0xc448ad98ffcc9ea9feb368bd29ab5cc57e74cc52ca1622c82e1d7874878191f9"),
    // tx_end_foreign_context
    word!("0xaa0018aa8da890b73511879487f65553753fb7df22de380dd84c11e6f77eec6f"),
    // tx_get_expiration_delta
    word!("0xa60286e820a755128b2269db5057b0e2d9b79fef6f813bf3fe3337553a8fbb53"),
    // tx_update_expiration_block_delta
    word!("0xa16440a9a8cd2a6d0ff7f5c3bcce2958976e5d3e6e8a6935ff40ae1863c324f0"),
];
